sudo: false
language: node_js
node_js:
  - "6.0"

before_install:
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = true ]; then openssl aes-256-cbc -K $encrypted_d9f08a58d46a_key -iv $encrypted_d9f08a58d46a_iv -in keyfile.json.enc -out keyfile.json -d; fi'

script:
  - npm run lint
  - npm run coverage
